---
output:
  word_document: default
  html_document: default
---
# Checking Column Requirements for DB

Loading the correct libraries and dataset

```{r}
library(tidyverse)
library(readxl)
library(hot.deck)
Class_Dataset_for_digital_badge <- read_excel("Class Dataset for digital badge.xlsx")
```
Checking the Requirements


```{r}
count_numeric <- length(select_if(Class_Dataset_for_digital_badge,is.numeric)) 
count_cat <- length(select_if(Class_Dataset_for_digital_badge,is.character))


dis_count <- 0
cont_count <- 0
for (i in colnames(Class_Dataset_for_digital_badge)){
  if (is.factor(Class_Dataset_for_digital_badge[[i]])) {
    dis_count <- dis_count + 1
  } else if (is.numeric(Class_Dataset_for_digital_badge[[i]])) {
    # Continuous if there are many unique values
    if (length(unique(Class_Dataset_for_digital_badge[[i]])) > 20) {
      cont_count <- cont_count + 1
    } else {
      dis_count <- dis_count + 1
    }
  }
}


if (count_numeric < 2 & count_cat < 2){
  print("There must be at least two categorical columns and two numerical columns")
} else if (count_numeric < 2){
  print('There needs to be at least two numerical columns')
}else if (count_cat < 2){
  print('There needs to be at least two categorical columns')
}else {
  print('The requirements have been satisifed')  
  }
```


Some Statistical Tests
```{r}

Class_Dataset_for_digital_badge$TreatmentID <- NA
for (i in seq_len(nrow(Class_Dataset_for_digital_badge))){
  if (Class_Dataset_for_digital_badge$Treatment[i] == 'Cont'){
    Class_Dataset_for_digital_badge$TreatmentID[i] <- 1
  } else if (Class_Dataset_for_digital_badge$Treatment[i] == 'CBT'){
    Class_Dataset_for_digital_badge$TreatmentID[i] <- 2
  }
}
Age_sum <- summary(Class_Dataset_for_digital_badge$Age)
print(Age_sum)

t.test(Class_Dataset_for_digital_badge$Pre_Weight,Class_Dataset_for_digital_badge$Post_Weight)
t.test(Class_Dataset_for_digital_badge$Pre_Weight)

summary(lm(data=Class_Dataset_for_digital_badge, formula = Post_Weight ~ Gender + Age + TreatmentID))
```

```{r}
BadgeDB2 <- pivot_longer(data=Class_Dataset_for_digital_badge, cols = 'Pre_Weight':'Post_Weight', values_to = 'Weight', names_to = "Pre/Post")

BadgeDB2$PatientID <- NA
count = 1
ID = 1
for (i in seq_len(nrow(BadgeDB2))){
  if (count %% 2 == 0) {
    BadgeDB2$PatientID[i] <-ID
    ID <- ID +1
    count <- count -1
  }
  else{
    BadgeDB2$PatientID[i] <-ID
    count <- count + 1
  }
  
}


ggplot(data = BadgeDB2[1:20,], mapping = aes( x=PatientID ,y = Weight, 
                                              color = `Pre/Post`)) +
  geom_point()  +
  scale_y_continuous(name="Weight in LBs") +
  labs(title = 'Changes in Weight', x = "Patient ID")


```
```{r}
for (i in colnames(Class_Dataset_for_digital_badge)){
  print(i)
}
print(all(Class_Dataset_for_digital_badge[["Pre_Weight"]] == round(Class_Dataset_for_digital_badge[["Pre_Weight"]])))
```

